apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: genai-chatbot
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
    - name: 'configmap'
      orgId: 1
      folder: 'GenAI Chatbot'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /etc/grafana/provisioning/dashboards
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      isDefault: true
      editable: true
      jsonData:
        timeInterval: "15s"
  grafana.ini: |
    [server]
    http_port = 3000
    domain = localhost
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
    serve_from_sub_path = true

    [security]
    admin_user = admin
    admin_password = admin
    allow_embedding = true

    [users]
    allow_sign_up = false

    [auth.anonymous]
    enabled = false

    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/genai-chatbot-dashboard.json

    [provisioning]
    dashboards = /etc/grafana/provisioning/dashboards
    datasources = /etc/grafana/provisioning/datasources 