apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk17
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50000
          name: jnlp
        env:
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false"
        - name: JENKINS_OPTS
          value: "--prefix=/jenkins"
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-config
<<<<<<< HEAD
          mountPath: /var/jenkins_home/init.groovy.d/
          subPath: init.groovy
        - name: jenkins-webhook-config
          mountPath: /var/jenkins_home/init.groovy.d/
          subPath: webhook.groovy
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: kubectl-config
          mountPath: /root/.kube
        - name: tools-script
          mountPath: /usr/local/bin/setup-tools.sh
          subPath: setup-tools.sh
        command: ["/bin/bash"]
        args: ["-c", "apt-get update && apt-get install -y python3 python3-pip curl git && chmod +x /usr/local/bin/setup-tools.sh && /usr/local/bin/setup-tools.sh && /usr/local/bin/jenkins.sh"]
=======
          mountPath: /var/jenkins_home/init.groovy.d
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /jenkins/login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /jenkins/login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
>>>>>>> b21476e553ea4597ddea74104c8c93d79701bee6
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: jenkins-config
        configMap:
<<<<<<< HEAD
          name: jenkins-config
      - name: jenkins-webhook-config
        configMap:
          name: jenkins-webhook-config
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: kubectl-config
        hostPath:
          path: /root/.kube
      - name: tools-script
        configMap:
          name: jenkins-tools-config 
=======
          name: jenkins-config 
>>>>>>> b21476e553ea4597ddea74104c8c93d79701bee6
