apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: genai-chatbot
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'genai-chatbot'
        static_configs:
          - targets: ['genai-chatbot-service:80']
        metrics_path: '/metrics'
        scrape_interval: 10s

      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana-service:3000']
        metrics_path: '/metrics'
        scrape_interval: 30s 