apiVersion: v1
kind: Secret
metadata:
  name: genai-chatbot-secrets
  namespace: genai-chatbot
type: Opaque
data:
  # Base64 encoded OpenAI API key
  # To encode your API key: echo -n "your-api-key-here" | base64
  OPENAI_API_KEY: "eW91ci1vcGVuYWktYXBpLWtleS1oZXJl"
stringData:
  # Alternative way to specify secrets (not base64 encoded)
  # OPENAI_API_KEY: "your-openai-api-key-here" 